package com.cqupt.dao.oracle;

import com.cqupt.entity.HAdministrator;
import com.cqupt.entity.HAdministratorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface HAdministratorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_administrator
     *
     * @mbg.generated Sun Apr 17 15:27:43 CST 2022
     */
    long countByExample(HAdministratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_administrator
     *
     * @mbg.generated Sun Apr 17 15:27:43 CST 2022
     */
    int deleteByExample(HAdministratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_administrator
     *
     * @mbg.generated Sun Apr 17 15:27:43 CST 2022
     */
    int deleteByPrimaryKey(Integer hAdminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_administrator
     *
     * @mbg.generated Sun Apr 17 15:27:43 CST 2022
     */
    int insert(HAdministrator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_administrator
     *
     * @mbg.generated Sun Apr 17 15:27:43 CST 2022
     */
    int insertSelective(HAdministrator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_administrator
     *
     * @mbg.generated Sun Apr 17 15:27:43 CST 2022
     */
    List<HAdministrator> selectByExample(HAdministratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_administrator
     *
     * @mbg.generated Sun Apr 17 15:27:43 CST 2022
     */
    HAdministrator selectByPrimaryKey(Integer hAdminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_administrator
     *
     * @mbg.generated Sun Apr 17 15:27:43 CST 2022
     */
    int updateByExampleSelective(@Param("record") HAdministrator record, @Param("example") HAdministratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_administrator
     *
     * @mbg.generated Sun Apr 17 15:27:43 CST 2022
     */
    int updateByExample(@Param("record") HAdministrator record, @Param("example") HAdministratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_administrator
     *
     * @mbg.generated Sun Apr 17 15:27:43 CST 2022
     */
    int updateByPrimaryKeySelective(HAdministrator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_administrator
     *
     * @mbg.generated Sun Apr 17 15:27:43 CST 2022
     */
    int updateByPrimaryKey(HAdministrator record);
}