package com.cqupt.dao.oracle;

import com.cqupt.entity.PurchaseList;
import com.cqupt.entity.PurchaseListExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface PurchaseListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_list
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    long countByExample(PurchaseListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_list
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    int deleteByExample(PurchaseListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_list
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    int deleteByPrimaryKey(Integer pId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_list
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    int insert(PurchaseList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_list
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    int insertSelective(PurchaseList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_list
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    List<PurchaseList> selectByExample(PurchaseListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_list
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    PurchaseList selectByPrimaryKey(Integer pId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_list
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    int updateByExampleSelective(@Param("record") PurchaseList record, @Param("example") PurchaseListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_list
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    int updateByExample(@Param("record") PurchaseList record, @Param("example") PurchaseListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_list
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    int updateByPrimaryKeySelective(PurchaseList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_list
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    int updateByPrimaryKey(PurchaseList record);
}