package com.cqupt.dao.oracle;

import com.cqupt.entity.StoreGoods;
import com.cqupt.entity.StoreGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface StoreGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_goods
     *
     * @mbg.generated Tue Apr 19 16:19:20 CST 2022
     */
    long countByExample(StoreGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_goods
     *
     * @mbg.generated Tue Apr 19 16:19:20 CST 2022
     */
    int deleteByExample(StoreGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_goods
     *
     * @mbg.generated Tue Apr 19 16:19:20 CST 2022
     */
    int deleteByPrimaryKey(Integer gId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_goods
     *
     * @mbg.generated Tue Apr 19 16:19:20 CST 2022
     */
    int insert(StoreGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_goods
     *
     * @mbg.generated Tue Apr 19 16:19:20 CST 2022
     */
    int insertSelective(StoreGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_goods
     *
     * @mbg.generated Tue Apr 19 16:19:20 CST 2022
     */
    List<StoreGoods> selectByExample(StoreGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_goods
     *
     * @mbg.generated Tue Apr 19 16:19:20 CST 2022
     */
    StoreGoods selectByPrimaryKey(Integer gId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_goods
     *
     * @mbg.generated Tue Apr 19 16:19:20 CST 2022
     */
    int updateByExampleSelective(@Param("record") StoreGoods record, @Param("example") StoreGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_goods
     *
     * @mbg.generated Tue Apr 19 16:19:20 CST 2022
     */
    int updateByExample(@Param("record") StoreGoods record, @Param("example") StoreGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_goods
     *
     * @mbg.generated Tue Apr 19 16:19:20 CST 2022
     */
    int updateByPrimaryKeySelective(StoreGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_goods
     *
     * @mbg.generated Tue Apr 19 16:19:20 CST 2022
     */
    int updateByPrimaryKey(StoreGoods record);
}