package com.cqupt.dao.oracle;

import com.cqupt.entity.TransportVehicle;
import com.cqupt.entity.TransportVehicleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface TransportVehicleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_vehicle
     *
     * @mbg.generated Mon Apr 18 15:55:29 CST 2022
     */
    long countByExample(TransportVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_vehicle
     *
     * @mbg.generated Mon Apr 18 15:55:29 CST 2022
     */
    int deleteByExample(TransportVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_vehicle
     *
     * @mbg.generated Mon Apr 18 15:55:29 CST 2022
     */
    int deleteByPrimaryKey(Integer vId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_vehicle
     *
     * @mbg.generated Mon Apr 18 15:55:29 CST 2022
     */
    int insert(TransportVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_vehicle
     *
     * @mbg.generated Mon Apr 18 15:55:29 CST 2022
     */
    int insertSelective(TransportVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_vehicle
     *
     * @mbg.generated Mon Apr 18 15:55:29 CST 2022
     */
    List<TransportVehicle> selectByExample(TransportVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_vehicle
     *
     * @mbg.generated Mon Apr 18 15:55:29 CST 2022
     */
    TransportVehicle selectByPrimaryKey(Integer vId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_vehicle
     *
     * @mbg.generated Mon Apr 18 15:55:29 CST 2022
     */
    int updateByExampleSelective(@Param("record") TransportVehicle record, @Param("example") TransportVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_vehicle
     *
     * @mbg.generated Mon Apr 18 15:55:29 CST 2022
     */
    int updateByExample(@Param("record") TransportVehicle record, @Param("example") TransportVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_vehicle
     *
     * @mbg.generated Mon Apr 18 15:55:29 CST 2022
     */
    int updateByPrimaryKeySelective(TransportVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_vehicle
     *
     * @mbg.generated Mon Apr 18 15:55:29 CST 2022
     */
    int updateByPrimaryKey(TransportVehicle record);
}