package com.cqupt.dao.oracle;

import com.cqupt.entity.TransportPlan;
import com.cqupt.entity.TransportPlanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface TransportPlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_plan
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    long countByExample(TransportPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_plan
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    int deleteByExample(TransportPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_plan
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    int deleteByPrimaryKey(Integer tpId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_plan
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    int insert(TransportPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_plan
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    int insertSelective(TransportPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_plan
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    List<TransportPlan> selectByExample(TransportPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_plan
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    TransportPlan selectByPrimaryKey(Integer tpId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_plan
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    int updateByExampleSelective(@Param("record") TransportPlan record, @Param("example") TransportPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_plan
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    int updateByExample(@Param("record") TransportPlan record, @Param("example") TransportPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_plan
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    int updateByPrimaryKeySelective(TransportPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_plan
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    int updateByPrimaryKey(TransportPlan record);
}