package com.cqupt.entity;

public class HAdministrator {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_administrator.h_admin_id
     *
     * @mbg.generated Sun Apr 17 15:27:43 CST 2022
     */
    private Integer hAdminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_administrator.h_admin_name
     *
     * @mbg.generated Sun Apr 17 15:27:43 CST 2022
     */
    private String hAdminName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_administrator.h_admin_pwd
     *
     * @mbg.generated Sun Apr 17 15:27:43 CST 2022
     */
    private String hAdminPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_administrator.h_admin_phone
     *
     * @mbg.generated Sun Apr 17 15:27:43 CST 2022
     */
    private Integer hAdminPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_administrator.h_admin_gender
     *
     * @mbg.generated Sun Apr 17 15:27:43 CST 2022
     */
    private String hAdminGender;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_administrator.h_admin_id
     *
     * @return the value of h_administrator.h_admin_id
     *
     * @mbg.generated Sun Apr 17 15:27:43 CST 2022
     */
    public Integer gethAdminId() {
        return hAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_administrator.h_admin_id
     *
     * @param hAdminId the value for h_administrator.h_admin_id
     *
     * @mbg.generated Sun Apr 17 15:27:43 CST 2022
     */
    public void sethAdminId(Integer hAdminId) {
        this.hAdminId = hAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_administrator.h_admin_name
     *
     * @return the value of h_administrator.h_admin_name
     *
     * @mbg.generated Sun Apr 17 15:27:43 CST 2022
     */
    public String gethAdminName() {
        return hAdminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_administrator.h_admin_name
     *
     * @param hAdminName the value for h_administrator.h_admin_name
     *
     * @mbg.generated Sun Apr 17 15:27:43 CST 2022
     */
    public void sethAdminName(String hAdminName) {
        this.hAdminName = hAdminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_administrator.h_admin_pwd
     *
     * @return the value of h_administrator.h_admin_pwd
     *
     * @mbg.generated Sun Apr 17 15:27:43 CST 2022
     */
    public String gethAdminPwd() {
        return hAdminPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_administrator.h_admin_pwd
     *
     * @param hAdminPwd the value for h_administrator.h_admin_pwd
     *
     * @mbg.generated Sun Apr 17 15:27:43 CST 2022
     */
    public void sethAdminPwd(String hAdminPwd) {
        this.hAdminPwd = hAdminPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_administrator.h_admin_phone
     *
     * @return the value of h_administrator.h_admin_phone
     *
     * @mbg.generated Sun Apr 17 15:27:43 CST 2022
     */
    public Integer gethAdminPhone() {
        return hAdminPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_administrator.h_admin_phone
     *
     * @param hAdminPhone the value for h_administrator.h_admin_phone
     *
     * @mbg.generated Sun Apr 17 15:27:43 CST 2022
     */
    public void sethAdminPhone(Integer hAdminPhone) {
        this.hAdminPhone = hAdminPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_administrator.h_admin_gender
     *
     * @return the value of h_administrator.h_admin_gender
     *
     * @mbg.generated Sun Apr 17 15:27:43 CST 2022
     */
    public String gethAdminGender() {
        return hAdminGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_administrator.h_admin_gender
     *
     * @param hAdminGender the value for h_administrator.h_admin_gender
     *
     * @mbg.generated Sun Apr 17 15:27:43 CST 2022
     */
    public void sethAdminGender(String hAdminGender) {
        this.hAdminGender = hAdminGender;
    }
}