package com.cqupt.entity;

public class PurchaseList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_list.p_id
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    private Integer pId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_list.supplier_id
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    private Integer supplierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_list.supplier_name
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    private String supplierName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_list.g_id
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    private Integer gId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_list.g_name
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    private String gName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_list.p_g_number
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    private Integer pGNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_list.p_id
     *
     * @return the value of purchase_list.p_id
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_list.p_id
     *
     * @param pId the value for purchase_list.p_id
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_list.supplier_id
     *
     * @return the value of purchase_list.supplier_id
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    public Integer getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_list.supplier_id
     *
     * @param supplierId the value for purchase_list.supplier_id
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_list.supplier_name
     *
     * @return the value of purchase_list.supplier_name
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    public String getSupplierName() {
        return supplierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_list.supplier_name
     *
     * @param supplierName the value for purchase_list.supplier_name
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_list.g_id
     *
     * @return the value of purchase_list.g_id
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    public Integer getgId() {
        return gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_list.g_id
     *
     * @param gId the value for purchase_list.g_id
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    public void setgId(Integer gId) {
        this.gId = gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_list.g_name
     *
     * @return the value of purchase_list.g_name
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    public String getgName() {
        return gName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_list.g_name
     *
     * @param gName the value for purchase_list.g_name
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    public void setgName(String gName) {
        this.gName = gName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_list.p_g_number
     *
     * @return the value of purchase_list.p_g_number
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    public Integer getpGNumber() {
        return pGNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_list.p_g_number
     *
     * @param pGNumber the value for purchase_list.p_g_number
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    public void setpGNumber(Integer pGNumber) {
        this.pGNumber = pGNumber;
    }
}