package com.cqupt.entity;

public class Store {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.store_id
     *
     * @mbg.generated Sun Apr 17 19:00:01 CST 2022
     */
    private Integer storeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.store_name
     *
     * @mbg.generated Sun Apr 17 19:00:01 CST 2022
     */
    private String storeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.store_address
     *
     * @mbg.generated Sun Apr 17 19:00:01 CST 2022
     */
    private String storeAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.store_password
     *
     * @mbg.generated Sun Apr 17 19:00:01 CST 2022
     */
    private String storePassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.store_phone
     *
     * @mbg.generated Sun Apr 17 19:00:01 CST 2022
     */
    private Integer storePhone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.store_id
     *
     * @return the value of store.store_id
     *
     * @mbg.generated Sun Apr 17 19:00:01 CST 2022
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.store_id
     *
     * @param storeId the value for store.store_id
     *
     * @mbg.generated Sun Apr 17 19:00:01 CST 2022
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.store_name
     *
     * @return the value of store.store_name
     *
     * @mbg.generated Sun Apr 17 19:00:01 CST 2022
     */
    public String getStoreName() {
        return storeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.store_name
     *
     * @param storeName the value for store.store_name
     *
     * @mbg.generated Sun Apr 17 19:00:01 CST 2022
     */
    public void setStoreName(String storeName) {
        this.storeName = storeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.store_address
     *
     * @return the value of store.store_address
     *
     * @mbg.generated Sun Apr 17 19:00:01 CST 2022
     */
    public String getStoreAddress() {
        return storeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.store_address
     *
     * @param storeAddress the value for store.store_address
     *
     * @mbg.generated Sun Apr 17 19:00:01 CST 2022
     */
    public void setStoreAddress(String storeAddress) {
        this.storeAddress = storeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.store_password
     *
     * @return the value of store.store_password
     *
     * @mbg.generated Sun Apr 17 19:00:01 CST 2022
     */
    public String getStorePassword() {
        return storePassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.store_password
     *
     * @param storePassword the value for store.store_password
     *
     * @mbg.generated Sun Apr 17 19:00:01 CST 2022
     */
    public void setStorePassword(String storePassword) {
        this.storePassword = storePassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.store_phone
     *
     * @return the value of store.store_phone
     *
     * @mbg.generated Sun Apr 17 19:00:01 CST 2022
     */
    public Integer getStorePhone() {
        return storePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.store_phone
     *
     * @param storePhone the value for store.store_phone
     *
     * @mbg.generated Sun Apr 17 19:00:01 CST 2022
     */
    public void setStorePhone(Integer storePhone) {
        this.storePhone = storePhone;
    }
}