package com.cqupt.entity;

public class StoreGoods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_goods.g_id
     *
     * @mbg.generated Tue Apr 19 16:19:20 CST 2022
     */
    private Integer gId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_goods.store_id
     *
     * @mbg.generated Tue Apr 19 16:19:20 CST 2022
     */
    private Integer storeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_goods.g_name
     *
     * @mbg.generated Tue Apr 19 16:19:20 CST 2022
     */
    private String gName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_goods.g_number
     *
     * @mbg.generated Tue Apr 19 16:19:20 CST 2022
     */
    private Integer gNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_goods.g_price
     *
     * @mbg.generated Tue Apr 19 16:19:20 CST 2022
     */
    private Float gPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_goods.g_id
     *
     * @return the value of store_goods.g_id
     *
     * @mbg.generated Tue Apr 19 16:19:20 CST 2022
     */
    public Integer getgId() {
        return gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_goods.g_id
     *
     * @param gId the value for store_goods.g_id
     *
     * @mbg.generated Tue Apr 19 16:19:20 CST 2022
     */
    public void setgId(Integer gId) {
        this.gId = gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_goods.store_id
     *
     * @return the value of store_goods.store_id
     *
     * @mbg.generated Tue Apr 19 16:19:20 CST 2022
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_goods.store_id
     *
     * @param storeId the value for store_goods.store_id
     *
     * @mbg.generated Tue Apr 19 16:19:20 CST 2022
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_goods.g_name
     *
     * @return the value of store_goods.g_name
     *
     * @mbg.generated Tue Apr 19 16:19:20 CST 2022
     */
    public String getgName() {
        return gName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_goods.g_name
     *
     * @param gName the value for store_goods.g_name
     *
     * @mbg.generated Tue Apr 19 16:19:20 CST 2022
     */
    public void setgName(String gName) {
        this.gName = gName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_goods.g_number
     *
     * @return the value of store_goods.g_number
     *
     * @mbg.generated Tue Apr 19 16:19:20 CST 2022
     */
    public Integer getgNumber() {
        return gNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_goods.g_number
     *
     * @param gNumber the value for store_goods.g_number
     *
     * @mbg.generated Tue Apr 19 16:19:20 CST 2022
     */
    public void setgNumber(Integer gNumber) {
        this.gNumber = gNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_goods.g_price
     *
     * @return the value of store_goods.g_price
     *
     * @mbg.generated Tue Apr 19 16:19:20 CST 2022
     */
    public Float getgPrice() {
        return gPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_goods.g_price
     *
     * @param gPrice the value for store_goods.g_price
     *
     * @mbg.generated Tue Apr 19 16:19:20 CST 2022
     */
    public void setgPrice(Float gPrice) {
        this.gPrice = gPrice;
    }
}