package com.cqupt.entity;

public class SupplierStore {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_store.ss_id
     *
     * @mbg.generated Wed May 04 15:45:50 CST 2022
     */
    private Integer ssId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_store.supplier_id
     *
     * @mbg.generated Wed May 04 15:45:50 CST 2022
     */
    private Integer supplierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_store.store_id
     *
     * @mbg.generated Wed May 04 15:45:50 CST 2022
     */
    private Integer storeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_store.transport_price
     *
     * @mbg.generated Wed May 04 15:45:50 CST 2022
     */
    private Float transportPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_store.ss_id
     *
     * @return the value of supplier_store.ss_id
     *
     * @mbg.generated Wed May 04 15:45:50 CST 2022
     */
    public Integer getSsId() {
        return ssId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_store.ss_id
     *
     * @param ssId the value for supplier_store.ss_id
     *
     * @mbg.generated Wed May 04 15:45:50 CST 2022
     */
    public void setSsId(Integer ssId) {
        this.ssId = ssId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_store.supplier_id
     *
     * @return the value of supplier_store.supplier_id
     *
     * @mbg.generated Wed May 04 15:45:50 CST 2022
     */
    public Integer getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_store.supplier_id
     *
     * @param supplierId the value for supplier_store.supplier_id
     *
     * @mbg.generated Wed May 04 15:45:50 CST 2022
     */
    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_store.store_id
     *
     * @return the value of supplier_store.store_id
     *
     * @mbg.generated Wed May 04 15:45:50 CST 2022
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_store.store_id
     *
     * @param storeId the value for supplier_store.store_id
     *
     * @mbg.generated Wed May 04 15:45:50 CST 2022
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_store.transport_price
     *
     * @return the value of supplier_store.transport_price
     *
     * @mbg.generated Wed May 04 15:45:50 CST 2022
     */
    public Float getTransportPrice() {
        return transportPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_store.transport_price
     *
     * @param transportPrice the value for supplier_store.transport_price
     *
     * @mbg.generated Wed May 04 15:45:50 CST 2022
     */
    public void setTransportPrice(Float transportPrice) {
        this.transportPrice = transportPrice;
    }
}