package com.cqupt.entity;

public class TransportVehicle {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transport_vehicle.v_id
     *
     * @mbg.generated Mon Apr 18 15:55:29 CST 2022
     */
    private Integer vId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transport_vehicle.h_admin_id
     *
     * @mbg.generated Mon Apr 18 15:55:29 CST 2022
     */
    private String hAdminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transport_vehicle.v_person
     *
     * @mbg.generated Mon Apr 18 15:55:29 CST 2022
     */
    private String vPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transport_vehicle.v_number
     *
     * @mbg.generated Mon Apr 18 15:55:29 CST 2022
     */
    private String vNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transport_vehicle.v_phone
     *
     * @mbg.generated Mon Apr 18 15:55:29 CST 2022
     */
    private Long vPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transport_vehicle.v_available
     *
     * @mbg.generated Mon Apr 18 15:55:29 CST 2022
     */
    private Boolean vAvailable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transport_vehicle.v_capacity
     *
     * @mbg.generated Mon Apr 18 15:55:29 CST 2022
     */
    private Integer vCapacity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transport_vehicle.v_id
     *
     * @return the value of transport_vehicle.v_id
     *
     * @mbg.generated Mon Apr 18 15:55:29 CST 2022
     */
    public Integer getvId() {
        return vId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transport_vehicle.v_id
     *
     * @param vId the value for transport_vehicle.v_id
     *
     * @mbg.generated Mon Apr 18 15:55:29 CST 2022
     */
    public void setvId(Integer vId) {
        this.vId = vId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transport_vehicle.h_admin_id
     *
     * @return the value of transport_vehicle.h_admin_id
     *
     * @mbg.generated Mon Apr 18 15:55:29 CST 2022
     */
    public String gethAdminId() {
        return hAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transport_vehicle.h_admin_id
     *
     * @param hAdminId the value for transport_vehicle.h_admin_id
     *
     * @mbg.generated Mon Apr 18 15:55:29 CST 2022
     */
    public void sethAdminId(String hAdminId) {
        this.hAdminId = hAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transport_vehicle.v_person
     *
     * @return the value of transport_vehicle.v_person
     *
     * @mbg.generated Mon Apr 18 15:55:29 CST 2022
     */
    public String getvPerson() {
        return vPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transport_vehicle.v_person
     *
     * @param vPerson the value for transport_vehicle.v_person
     *
     * @mbg.generated Mon Apr 18 15:55:29 CST 2022
     */
    public void setvPerson(String vPerson) {
        this.vPerson = vPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transport_vehicle.v_number
     *
     * @return the value of transport_vehicle.v_number
     *
     * @mbg.generated Mon Apr 18 15:55:29 CST 2022
     */
    public String getvNumber() {
        return vNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transport_vehicle.v_number
     *
     * @param vNumber the value for transport_vehicle.v_number
     *
     * @mbg.generated Mon Apr 18 15:55:29 CST 2022
     */
    public void setvNumber(String vNumber) {
        this.vNumber = vNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transport_vehicle.v_phone
     *
     * @return the value of transport_vehicle.v_phone
     *
     * @mbg.generated Mon Apr 18 15:55:29 CST 2022
     */
    public Long getvPhone() {
        return vPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transport_vehicle.v_phone
     *
     * @param vPhone the value for transport_vehicle.v_phone
     *
     * @mbg.generated Mon Apr 18 15:55:29 CST 2022
     */
    public void setvPhone(Long vPhone) {
        this.vPhone = vPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transport_vehicle.v_available
     *
     * @return the value of transport_vehicle.v_available
     *
     * @mbg.generated Mon Apr 18 15:55:29 CST 2022
     */
    public Boolean getvAvailable() {
        return vAvailable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transport_vehicle.v_available
     *
     * @param vAvailable the value for transport_vehicle.v_available
     *
     * @mbg.generated Mon Apr 18 15:55:29 CST 2022
     */
    public void setvAvailable(Boolean vAvailable) {
        this.vAvailable = vAvailable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transport_vehicle.v_capacity
     *
     * @return the value of transport_vehicle.v_capacity
     *
     * @mbg.generated Mon Apr 18 15:55:29 CST 2022
     */
    public Integer getvCapacity() {
        return vCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transport_vehicle.v_capacity
     *
     * @param vCapacity the value for transport_vehicle.v_capacity
     *
     * @mbg.generated Mon Apr 18 15:55:29 CST 2022
     */
    public void setvCapacity(Integer vCapacity) {
        this.vCapacity = vCapacity;
    }
}