package com.cqupt.entity;

import java.util.ArrayList;
import java.util.List;

public class TransportVehicleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table transport_vehicle
     *
     * @mbg.generated Mon Apr 18 15:55:29 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table transport_vehicle
     *
     * @mbg.generated Mon Apr 18 15:55:29 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table transport_vehicle
     *
     * @mbg.generated Mon Apr 18 15:55:29 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_vehicle
     *
     * @mbg.generated Mon Apr 18 15:55:29 CST 2022
     */
    public TransportVehicleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_vehicle
     *
     * @mbg.generated Mon Apr 18 15:55:29 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_vehicle
     *
     * @mbg.generated Mon Apr 18 15:55:29 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_vehicle
     *
     * @mbg.generated Mon Apr 18 15:55:29 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_vehicle
     *
     * @mbg.generated Mon Apr 18 15:55:29 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_vehicle
     *
     * @mbg.generated Mon Apr 18 15:55:29 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_vehicle
     *
     * @mbg.generated Mon Apr 18 15:55:29 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_vehicle
     *
     * @mbg.generated Mon Apr 18 15:55:29 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_vehicle
     *
     * @mbg.generated Mon Apr 18 15:55:29 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_vehicle
     *
     * @mbg.generated Mon Apr 18 15:55:29 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_vehicle
     *
     * @mbg.generated Mon Apr 18 15:55:29 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table transport_vehicle
     *
     * @mbg.generated Mon Apr 18 15:55:29 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andVIdIsNull() {
            addCriterion("v_id is null");
            return (Criteria) this;
        }

        public Criteria andVIdIsNotNull() {
            addCriterion("v_id is not null");
            return (Criteria) this;
        }

        public Criteria andVIdEqualTo(Integer value) {
            addCriterion("v_id =", value, "vId");
            return (Criteria) this;
        }

        public Criteria andVIdNotEqualTo(Integer value) {
            addCriterion("v_id <>", value, "vId");
            return (Criteria) this;
        }

        public Criteria andVIdGreaterThan(Integer value) {
            addCriterion("v_id >", value, "vId");
            return (Criteria) this;
        }

        public Criteria andVIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("v_id >=", value, "vId");
            return (Criteria) this;
        }

        public Criteria andVIdLessThan(Integer value) {
            addCriterion("v_id <", value, "vId");
            return (Criteria) this;
        }

        public Criteria andVIdLessThanOrEqualTo(Integer value) {
            addCriterion("v_id <=", value, "vId");
            return (Criteria) this;
        }

        public Criteria andVIdIn(List<Integer> values) {
            addCriterion("v_id in", values, "vId");
            return (Criteria) this;
        }

        public Criteria andVIdNotIn(List<Integer> values) {
            addCriterion("v_id not in", values, "vId");
            return (Criteria) this;
        }

        public Criteria andVIdBetween(Integer value1, Integer value2) {
            addCriterion("v_id between", value1, value2, "vId");
            return (Criteria) this;
        }

        public Criteria andVIdNotBetween(Integer value1, Integer value2) {
            addCriterion("v_id not between", value1, value2, "vId");
            return (Criteria) this;
        }

        public Criteria andHAdminIdIsNull() {
            addCriterion("h_admin_id is null");
            return (Criteria) this;
        }

        public Criteria andHAdminIdIsNotNull() {
            addCriterion("h_admin_id is not null");
            return (Criteria) this;
        }

        public Criteria andHAdminIdEqualTo(String value) {
            addCriterion("h_admin_id =", value, "hAdminId");
            return (Criteria) this;
        }

        public Criteria andHAdminIdNotEqualTo(String value) {
            addCriterion("h_admin_id <>", value, "hAdminId");
            return (Criteria) this;
        }

        public Criteria andHAdminIdGreaterThan(String value) {
            addCriterion("h_admin_id >", value, "hAdminId");
            return (Criteria) this;
        }

        public Criteria andHAdminIdGreaterThanOrEqualTo(String value) {
            addCriterion("h_admin_id >=", value, "hAdminId");
            return (Criteria) this;
        }

        public Criteria andHAdminIdLessThan(String value) {
            addCriterion("h_admin_id <", value, "hAdminId");
            return (Criteria) this;
        }

        public Criteria andHAdminIdLessThanOrEqualTo(String value) {
            addCriterion("h_admin_id <=", value, "hAdminId");
            return (Criteria) this;
        }

        public Criteria andHAdminIdLike(String value) {
            addCriterion("h_admin_id like", value, "hAdminId");
            return (Criteria) this;
        }

        public Criteria andHAdminIdNotLike(String value) {
            addCriterion("h_admin_id not like", value, "hAdminId");
            return (Criteria) this;
        }

        public Criteria andHAdminIdIn(List<String> values) {
            addCriterion("h_admin_id in", values, "hAdminId");
            return (Criteria) this;
        }

        public Criteria andHAdminIdNotIn(List<String> values) {
            addCriterion("h_admin_id not in", values, "hAdminId");
            return (Criteria) this;
        }

        public Criteria andHAdminIdBetween(String value1, String value2) {
            addCriterion("h_admin_id between", value1, value2, "hAdminId");
            return (Criteria) this;
        }

        public Criteria andHAdminIdNotBetween(String value1, String value2) {
            addCriterion("h_admin_id not between", value1, value2, "hAdminId");
            return (Criteria) this;
        }

        public Criteria andVPersonIsNull() {
            addCriterion("v_person is null");
            return (Criteria) this;
        }

        public Criteria andVPersonIsNotNull() {
            addCriterion("v_person is not null");
            return (Criteria) this;
        }

        public Criteria andVPersonEqualTo(String value) {
            addCriterion("v_person =", value, "vPerson");
            return (Criteria) this;
        }

        public Criteria andVPersonNotEqualTo(String value) {
            addCriterion("v_person <>", value, "vPerson");
            return (Criteria) this;
        }

        public Criteria andVPersonGreaterThan(String value) {
            addCriterion("v_person >", value, "vPerson");
            return (Criteria) this;
        }

        public Criteria andVPersonGreaterThanOrEqualTo(String value) {
            addCriterion("v_person >=", value, "vPerson");
            return (Criteria) this;
        }

        public Criteria andVPersonLessThan(String value) {
            addCriterion("v_person <", value, "vPerson");
            return (Criteria) this;
        }

        public Criteria andVPersonLessThanOrEqualTo(String value) {
            addCriterion("v_person <=", value, "vPerson");
            return (Criteria) this;
        }

        public Criteria andVPersonLike(String value) {
            addCriterion("v_person like", value, "vPerson");
            return (Criteria) this;
        }

        public Criteria andVPersonNotLike(String value) {
            addCriterion("v_person not like", value, "vPerson");
            return (Criteria) this;
        }

        public Criteria andVPersonIn(List<String> values) {
            addCriterion("v_person in", values, "vPerson");
            return (Criteria) this;
        }

        public Criteria andVPersonNotIn(List<String> values) {
            addCriterion("v_person not in", values, "vPerson");
            return (Criteria) this;
        }

        public Criteria andVPersonBetween(String value1, String value2) {
            addCriterion("v_person between", value1, value2, "vPerson");
            return (Criteria) this;
        }

        public Criteria andVPersonNotBetween(String value1, String value2) {
            addCriterion("v_person not between", value1, value2, "vPerson");
            return (Criteria) this;
        }

        public Criteria andVNumberIsNull() {
            addCriterion("v_number is null");
            return (Criteria) this;
        }

        public Criteria andVNumberIsNotNull() {
            addCriterion("v_number is not null");
            return (Criteria) this;
        }

        public Criteria andVNumberEqualTo(String value) {
            addCriterion("v_number =", value, "vNumber");
            return (Criteria) this;
        }

        public Criteria andVNumberNotEqualTo(String value) {
            addCriterion("v_number <>", value, "vNumber");
            return (Criteria) this;
        }

        public Criteria andVNumberGreaterThan(String value) {
            addCriterion("v_number >", value, "vNumber");
            return (Criteria) this;
        }

        public Criteria andVNumberGreaterThanOrEqualTo(String value) {
            addCriterion("v_number >=", value, "vNumber");
            return (Criteria) this;
        }

        public Criteria andVNumberLessThan(String value) {
            addCriterion("v_number <", value, "vNumber");
            return (Criteria) this;
        }

        public Criteria andVNumberLessThanOrEqualTo(String value) {
            addCriterion("v_number <=", value, "vNumber");
            return (Criteria) this;
        }

        public Criteria andVNumberLike(String value) {
            addCriterion("v_number like", value, "vNumber");
            return (Criteria) this;
        }

        public Criteria andVNumberNotLike(String value) {
            addCriterion("v_number not like", value, "vNumber");
            return (Criteria) this;
        }

        public Criteria andVNumberIn(List<String> values) {
            addCriterion("v_number in", values, "vNumber");
            return (Criteria) this;
        }

        public Criteria andVNumberNotIn(List<String> values) {
            addCriterion("v_number not in", values, "vNumber");
            return (Criteria) this;
        }

        public Criteria andVNumberBetween(String value1, String value2) {
            addCriterion("v_number between", value1, value2, "vNumber");
            return (Criteria) this;
        }

        public Criteria andVNumberNotBetween(String value1, String value2) {
            addCriterion("v_number not between", value1, value2, "vNumber");
            return (Criteria) this;
        }

        public Criteria andVPhoneIsNull() {
            addCriterion("v_phone is null");
            return (Criteria) this;
        }

        public Criteria andVPhoneIsNotNull() {
            addCriterion("v_phone is not null");
            return (Criteria) this;
        }

        public Criteria andVPhoneEqualTo(Long value) {
            addCriterion("v_phone =", value, "vPhone");
            return (Criteria) this;
        }

        public Criteria andVPhoneNotEqualTo(Long value) {
            addCriterion("v_phone <>", value, "vPhone");
            return (Criteria) this;
        }

        public Criteria andVPhoneGreaterThan(Long value) {
            addCriterion("v_phone >", value, "vPhone");
            return (Criteria) this;
        }

        public Criteria andVPhoneGreaterThanOrEqualTo(Long value) {
            addCriterion("v_phone >=", value, "vPhone");
            return (Criteria) this;
        }

        public Criteria andVPhoneLessThan(Long value) {
            addCriterion("v_phone <", value, "vPhone");
            return (Criteria) this;
        }

        public Criteria andVPhoneLessThanOrEqualTo(Long value) {
            addCriterion("v_phone <=", value, "vPhone");
            return (Criteria) this;
        }

        public Criteria andVPhoneIn(List<Long> values) {
            addCriterion("v_phone in", values, "vPhone");
            return (Criteria) this;
        }

        public Criteria andVPhoneNotIn(List<Long> values) {
            addCriterion("v_phone not in", values, "vPhone");
            return (Criteria) this;
        }

        public Criteria andVPhoneBetween(Long value1, Long value2) {
            addCriterion("v_phone between", value1, value2, "vPhone");
            return (Criteria) this;
        }

        public Criteria andVPhoneNotBetween(Long value1, Long value2) {
            addCriterion("v_phone not between", value1, value2, "vPhone");
            return (Criteria) this;
        }

        public Criteria andVAvailableIsNull() {
            addCriterion("v_available is null");
            return (Criteria) this;
        }

        public Criteria andVAvailableIsNotNull() {
            addCriterion("v_available is not null");
            return (Criteria) this;
        }

        public Criteria andVAvailableEqualTo(Boolean value) {
            addCriterion("v_available =", value, "vAvailable");
            return (Criteria) this;
        }

        public Criteria andVAvailableNotEqualTo(Boolean value) {
            addCriterion("v_available <>", value, "vAvailable");
            return (Criteria) this;
        }

        public Criteria andVAvailableGreaterThan(Boolean value) {
            addCriterion("v_available >", value, "vAvailable");
            return (Criteria) this;
        }

        public Criteria andVAvailableGreaterThanOrEqualTo(Boolean value) {
            addCriterion("v_available >=", value, "vAvailable");
            return (Criteria) this;
        }

        public Criteria andVAvailableLessThan(Boolean value) {
            addCriterion("v_available <", value, "vAvailable");
            return (Criteria) this;
        }

        public Criteria andVAvailableLessThanOrEqualTo(Boolean value) {
            addCriterion("v_available <=", value, "vAvailable");
            return (Criteria) this;
        }

        public Criteria andVAvailableIn(List<Boolean> values) {
            addCriterion("v_available in", values, "vAvailable");
            return (Criteria) this;
        }

        public Criteria andVAvailableNotIn(List<Boolean> values) {
            addCriterion("v_available not in", values, "vAvailable");
            return (Criteria) this;
        }

        public Criteria andVAvailableBetween(Boolean value1, Boolean value2) {
            addCriterion("v_available between", value1, value2, "vAvailable");
            return (Criteria) this;
        }

        public Criteria andVAvailableNotBetween(Boolean value1, Boolean value2) {
            addCriterion("v_available not between", value1, value2, "vAvailable");
            return (Criteria) this;
        }

        public Criteria andVCapacityIsNull() {
            addCriterion("v_capacity is null");
            return (Criteria) this;
        }

        public Criteria andVCapacityIsNotNull() {
            addCriterion("v_capacity is not null");
            return (Criteria) this;
        }

        public Criteria andVCapacityEqualTo(Integer value) {
            addCriterion("v_capacity =", value, "vCapacity");
            return (Criteria) this;
        }

        public Criteria andVCapacityNotEqualTo(Integer value) {
            addCriterion("v_capacity <>", value, "vCapacity");
            return (Criteria) this;
        }

        public Criteria andVCapacityGreaterThan(Integer value) {
            addCriterion("v_capacity >", value, "vCapacity");
            return (Criteria) this;
        }

        public Criteria andVCapacityGreaterThanOrEqualTo(Integer value) {
            addCriterion("v_capacity >=", value, "vCapacity");
            return (Criteria) this;
        }

        public Criteria andVCapacityLessThan(Integer value) {
            addCriterion("v_capacity <", value, "vCapacity");
            return (Criteria) this;
        }

        public Criteria andVCapacityLessThanOrEqualTo(Integer value) {
            addCriterion("v_capacity <=", value, "vCapacity");
            return (Criteria) this;
        }

        public Criteria andVCapacityIn(List<Integer> values) {
            addCriterion("v_capacity in", values, "vCapacity");
            return (Criteria) this;
        }

        public Criteria andVCapacityNotIn(List<Integer> values) {
            addCriterion("v_capacity not in", values, "vCapacity");
            return (Criteria) this;
        }

        public Criteria andVCapacityBetween(Integer value1, Integer value2) {
            addCriterion("v_capacity between", value1, value2, "vCapacity");
            return (Criteria) this;
        }

        public Criteria andVCapacityNotBetween(Integer value1, Integer value2) {
            addCriterion("v_capacity not between", value1, value2, "vCapacity");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table transport_vehicle
     *
     * @mbg.generated do_not_delete_during_merge Mon Apr 18 15:55:29 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table transport_vehicle
     *
     * @mbg.generated Mon Apr 18 15:55:29 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}