package com.cqupt.entity;

public class TransportPlan {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transport_plan.tp_id
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    private Integer tpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transport_plan.tp_p_id
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    private Integer tpPId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transport_plan.g_id
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    private Integer gId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transport_plan.supplier_id
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    private Integer supplierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transport_plan.store_id
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    private Integer storeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transport_plan.tp_number
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    private Integer tpNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transport_plan.tp_id
     *
     * @return the value of transport_plan.tp_id
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    public Integer getTpId() {
        return tpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transport_plan.tp_id
     *
     * @param tpId the value for transport_plan.tp_id
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    public void setTpId(Integer tpId) {
        this.tpId = tpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transport_plan.tp_p_id
     *
     * @return the value of transport_plan.tp_p_id
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    public Integer getTpPId() {
        return tpPId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transport_plan.tp_p_id
     *
     * @param tpPId the value for transport_plan.tp_p_id
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    public void setTpPId(Integer tpPId) {
        this.tpPId = tpPId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transport_plan.g_id
     *
     * @return the value of transport_plan.g_id
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    public Integer getgId() {
        return gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transport_plan.g_id
     *
     * @param gId the value for transport_plan.g_id
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    public void setgId(Integer gId) {
        this.gId = gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transport_plan.supplier_id
     *
     * @return the value of transport_plan.supplier_id
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    public Integer getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transport_plan.supplier_id
     *
     * @param supplierId the value for transport_plan.supplier_id
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transport_plan.store_id
     *
     * @return the value of transport_plan.store_id
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transport_plan.store_id
     *
     * @param storeId the value for transport_plan.store_id
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transport_plan.tp_number
     *
     * @return the value of transport_plan.tp_number
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    public Integer getTpNumber() {
        return tpNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transport_plan.tp_number
     *
     * @param tpNumber the value for transport_plan.tp_number
     *
     * @mbg.generated Mon May 02 21:44:16 CST 2022
     */
    public void setTpNumber(Integer tpNumber) {
        this.tpNumber = tpNumber;
    }
}